import sqlite3
import os
import sys
import hashlib
import time
import re
from datetime import datetime, timezone, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from skill_engine import skill
from cron_engine import CronManager

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data')
DB_PATH = os.path.join(DATA_DIR, 'todos.db')
MD_PATH = os.path.join(DATA_DIR, 'personal.md')

_db_initialized = False

def _ensure_schema():
    global _db_initialized
    if _db_initialized:
        return
    os.makedirs(DATA_DIR, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.execute('PRAGMA journal_mode=WAL')
    conn.execute('PRAGMA synchronous=NORMAL')
    conn.execute('PRAGMA foreign_keys=ON')
    
    # Create tables
    conn.execute("""
        CREATE TABLE IF NOT EXISTS todos (
          id TEXT PRIMARY KEY,
          title TEXT NOT NULL,
          description TEXT,
          status TEXT NOT NULL DEFAULT 'pending',
          kind TEXT NOT NULL DEFAULT 'misc',
          project TEXT,
          created_at TEXT NOT NULL,
          updated_at TEXT NOT NULL,
          started_at TEXT,
          snoozed_until TEXT,
          shelved_at TEXT,
          shelved_reason TEXT,
          completed_at TEXT,
          dropped_at TEXT,
          dropped_reason TEXT,
          due_at TEXT,
          notified_due_at TEXT,
          recur_cron TEXT,
          recur_parent_id TEXT,
          recur_last_spawned_at TEXT,
          created_via TEXT,
          source_message_id TEXT,
          dispatch_target TEXT,
          dispatch_payload_json TEXT,
          dispatch_last_run_at TEXT,
          FOREIGN KEY (recur_parent_id) REFERENCES todos(id) ON DELETE CASCADE
        )
    """)
    conn.execute("CREATE INDEX IF NOT EXISTS idx_todos_status ON todos(status, updated_at DESC)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_todos_project ON todos(project, status)")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_todos_wake ON todos(snoozed_until) WHERE status='snoozed'")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_todos_due ON todos(due_at) WHERE due_at IS NOT NULL AND notified_due_at IS NULL")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_todos_recur ON todos(kind, recur_last_spawned_at) WHERE kind='recurring'")
    
    conn.execute("PRAGMA user_version = 1")
    conn.commit()
    conn.close()
    _db_initialized = True

def _conn():
    _ensure_schema()
    conn = sqlite3.connect(DB_PATH)
    conn.execute('PRAGMA foreign_keys=ON')
    return conn

def _gen_id(title: str) -> str:
    base = hashlib.sha256(f"{title}-{time.time_ns()}".encode()).hexdigest()[:6]
    conn = _conn()
    cursor = conn.cursor()
    for attempt in range(5):
        candidate = base if attempt == 0 else hashlib.sha256(f"{base}-{attempt}".encode()).hexdigest()[:6]
        cursor.execute("SELECT 1 FROM todos WHERE id=?", (candidate,))
        if not cursor.fetchone():
            conn.close()
            return candidate
    conn.close()
    raise RuntimeError("ID collision after 5 attempts")

# Time utilities
def _now_iso():
    return datetime.now(timezone.utc).isoformat()

def _parse_until(until: str) -> str:
    if until.startswith('+'):
        m = re.match(r'^\+(\d+)([mhd])$', until)
        if m:
            n, unit = int(m.group(1)), m.group(2)
            delta = {'m': timedelta(minutes=n), 'h': timedelta(hours=n), 'd': timedelta(days=n)}[unit]
            return (datetime.now(timezone.utc) + delta).isoformat()
    try:
        dt = datetime.fromisoformat(until.replace('Z', '+00:00'))
        return dt.isoformat()
    except ValueError:
        raise ValueError(f"无法解析时间: {until!r}（支持 ISO8601 或 +Nm/+Nh/+Nd）")

def _render_markdown():
    conn = _conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM todos WHERE status != 'dropped' ORDER BY updated_at DESC")
    columns = [col[0] for col in cursor.description]
    todos = [dict(zip(columns, row)) for row in cursor.fetchall()]
    conn.close()
    
    grouped = {
        'active': [],
        'pending': [],
        'snoozed': [],
        'shelved': [],
        'done': []
    }
    now_dt = datetime.now(timezone.utc)
    
    for t in todos:
        st = t['status']
        if st == 'done':
            comp_dt = datetime.fromisoformat(t['completed_at'].replace('Z', '+00:00')) if t['completed_at'] else now_dt
            if (now_dt - comp_dt).days <= 7:
                grouped['done'].append(t)
        elif st in grouped:
            grouped[st].append(t)
            
    lines = [
        "<!-- AUTO-GENERATED by ops_todo. 不要手编，改动会被覆盖。 -->",
        "<!-- 增删改请通过 lite_agent 的飞书或钉钉对话使用 todo_xxx 技能。 -->",
        f"\n# Personal Todos · 最新同步: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
    ]
    
    def _format_todo(t):
        checkbox = "[x]" if t['status'] == 'done' else "[ ]"
        prefix = f"- {checkbox} `{t['id']}`"
        tags = []
        if t['kind'] != 'misc':
            tags.append(t['kind'])
        if t['project']:
            tags.append(f"proj:{t['project']}")
        tag_str = f" `[{','.join(tags)}]`" if tags else ""
        
        line = f"{prefix}{tag_str} {t['title']}"
        
        detail_lines = []
        if t['status'] == 'snoozed' and t['snoozed_until']:
            detail_lines.append(f"唤醒时间: {t['snoozed_until']}")
        if t['status'] == 'shelved' and t['shelved_reason']:
            detail_lines.append(f"搁置原因: {t['shelved_reason']}")
        if t['due_at']:
            detail_lines.append(f"到期时间: {t['due_at']}")
        if t['description']:
            detail_lines.append(t['description'])
            
        if detail_lines:
            detail_str = "\n  ".join(detail_lines)
            line += f"\n  <details><summary>详情</summary>\n\n  {detail_str}\n\n  </details>"
        return line
        
    labels = {
        'active': '进行中',
        'pending': '待办',
        'snoozed': '延期中',
        'shelved': '搁置',
        'done': '已完成（最近 7 天）'
    }
    
    for k in ['active', 'pending', 'snoozed', 'shelved', 'done']:
        if grouped[k]:
            lines.append(f"## {labels[k]}\n")
            for t in grouped[k]:
                lines.append(_format_todo(t))
            lines.append("")
            
    rendered = "\n".join(lines)
    tmp_path = MD_PATH + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(rendered)
    os.replace(tmp_path, MD_PATH)

def _update_todo_status(tid: str, status: str, extra_fields: dict = None):
    conn = _conn()
    now = _now_iso()
    fields = {"status": status, "updated_at": now}
    if extra_fields:
        fields.update(extra_fields)
        
    set_clause = ", ".join([f"{k}=?" for k in fields.keys()])
    values = list(fields.values()) + [tid]
    
    cursor = conn.cursor()
    cursor.execute(f"UPDATE todos SET {set_clause} WHERE id=?", values)
    rowcount = cursor.rowcount
    conn.commit()
    conn.close()
    
    if rowcount > 0:
        _render_markdown()
        return f"✅ 任务 {tid} 状态已更新为 {status}"
    return f"❌ 未找到任务 {tid}"

@skill(
    name="todo_add",
    description="添加一条新的待办事项",
    params={
        "title": {"type": "string", "description": "任务标题"},
        "kind": {"type": "string", "description": "分类: misc 或者是 code", "default": "misc"},
        "project": {"type": "string", "description": "关联项目名称，可选"},
        "description": {"type": "string", "description": "详细描述，可选"},
        "due_at": {"type": "string", "description": "到期时间必须是 ISO8601 且含时区，例如 2026-06-20T12:00:00+08:00，可选"}
    }
)
def todo_add(title: str, kind: str = "misc", project: str = None, description: str = None, due_at: str = None) -> str:
    if kind == "recurring":
        return "❌ 第一版 kind 仅接受 misc|code，传 recurring 直接拒绝；将来集成 cron_engine 时再开放"
    
    tid = _gen_id(title)
    now = _now_iso()
    
    conn = _conn()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO todos (id, title, description, status, kind, project, created_at, updated_at, due_at)
        VALUES (?, ?, ?, 'pending', ?, ?, ?, ?, ?)
    """, (tid, title, description, kind, project, now, now, due_at))
    conn.commit()
    conn.close()
    
    _render_markdown()
    return f"✅ 成功添加待办事项: {title} (ID: {tid})"

@skill(
    name="todo_list",
    description="查询待办事项列表",
    params={
        "status": {"type": "string", "description": "状态过滤，如 pending, active, done, 或逗号分隔", "default": "pending,active"},
        "project": {"type": "string", "description": "按项目过滤"},
        "kind": {"type": "string", "description": "按分类过滤"},
        "limit": {"type": "integer", "description": "限制返回数量", "default": 20}
    }
)
def todo_list(status: str = "pending,active", project: str = None, kind: str = None, limit: int = 20) -> str:
    conn = _conn()
    cursor = conn.cursor()
    
    query = "SELECT id, title, status, kind, project, due_at FROM todos WHERE 1=1"
    params = []
    
    if status and status != 'all':
        statuses = status.split(',')
        query += f" AND status IN ({','.join(['?'] * len(statuses))})"
        params.extend(statuses)
        
    if project:
        query += " AND project = ?"
        params.append(project)
        
    if kind:
        query += " AND kind = ?"
        params.append(kind)
        
    query += " ORDER BY updated_at DESC LIMIT ?"
    params.append(limit)
    
    cursor.execute(query, params)
    rows = cursor.fetchall()
    conn.close()
    
    if not rows:
        return "没有找到符合条件的待办事项。"
        
    result = []
    for r in rows:
        tags = [r[3]]
        if r[4]: tags.append(f"proj:{r[4]}")
        tag_str = f"[{','.join(tags)}]"
        due_str = f" (到期: {r[5]})" if r[5] else ""
        result.append(f"- [{r[2]}] {r[0]} {tag_str} {r[1]}{due_str}")
        
    return "\n".join(result)

@skill(name="todo_get", description="获取待办事项详情", params={"id": {"type": "string", "description": "任务 ID"}})
def todo_get(id: str) -> str:
    conn = _conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM todos WHERE id=?", (id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        return f"❌ 未找到任务 {id}"
        
    columns = [col[0] for col in cursor.description]
    t = dict(zip(columns, row))
    conn.close()
    
    res = [f"【任务详情】 ID: {t['id']}"]
    for k, v in t.items():
        if v is not None:
            res.append(f"{k}: {v}")
    return "\n".join(res)

@skill(name="todo_start", description="开始处理待办事项", params={"id": {"type": "string"}})
def todo_start(id: str) -> str:
    return _update_todo_status(id, "active", {"started_at": _now_iso()})

@skill(name="todo_done", description="将待办事项标记为完成", params={"id": {"type": "string"}})
def todo_done(id: str) -> str:
    return _update_todo_status(id, "done", {"completed_at": _now_iso()})

@skill(
    name="todo_drop", 
    description="放弃待办事项（不再做但保留记录）", 
    params={"id": {"type": "string"}, "reason": {"type": "string", "description": "放弃原因，可选"}}
)
def todo_drop(id: str, reason: str = None) -> str:
    return _update_todo_status(id, "dropped", {"dropped_at": _now_iso(), "dropped_reason": reason})

@skill(
    name="todo_snooze", 
    description="将任务延期挂起", 
    params={"id": {"type": "string"}, "until": {"type": "string", "description": "唤醒时间 ISO8601 格式或 +Nm/+Nh/+Nd 相对时间（如 +2m, +3d）"}}
)
def todo_snooze(id: str, until: str) -> str:
    try:
        dt = _parse_until(until)
    except ValueError as e:
        return f"❌ {e}"
    return _update_todo_status(id, "snoozed", {"snoozed_until": dt})

@skill(
    name="todo_shelve", 
    description="无限期搁置任务（不知何时做）", 
    params={"id": {"type": "string"}, "reason": {"type": "string", "description": "搁置原因，可选"}}
)
def todo_shelve(id: str, reason: str = None) -> str:
    return _update_todo_status(id, "shelved", {"shelved_at": _now_iso(), "shelved_reason": reason})

@skill(name="todo_resume", description="恢复被延期或搁置的任务为待办状态", params={"id": {"type": "string"}})
def todo_resume(id: str) -> str:
    return _update_todo_status(id, "pending", {
        "snoozed_until": None,
        "shelved_at": None,
        "shelved_reason": None
    })

@skill(
    name="todo_update", 
    description="修改任务的基本信息", 
    params={
        "id": {"type": "string"},
        "title": {"type": "string", "description": "新标题"},
        "description": {"type": "string", "description": "新详情"},
        "due_at": {"type": "string", "description": "新到期时间 ISO8601"},
        "project": {"type": "string", "description": "新项目"}
    }
)
def todo_update(id: str, title: str = None, description: str = None, due_at: str = None, project: str = None) -> str:
    conn = _conn()
    fields = {"updated_at": _now_iso()}
    if title is not None: fields["title"] = title
    if description is not None: fields["description"] = description
    if due_at is not None: fields["due_at"] = due_at
    if project is not None: fields["project"] = project
    
    set_clause = ", ".join([f"{k}=?" for k in fields.keys()])
    values = list(fields.values()) + [id]
    
    cursor = conn.cursor()
    cursor.execute(f"UPDATE todos SET {set_clause} WHERE id=?", values)
    rowcount = cursor.rowcount
    conn.commit()
    conn.close()
    
    if rowcount > 0:
        _render_markdown()
        return f"✅ 任务 {id} 已更新"
    return f"❌ 未找到任务 {id}"

@skill(name="todo_dispatch", description="派发代码任务以供本地 IDE 处理", params={"id": {"type": "string"}, "target": {"type": "string", "default": "manual"}})
def todo_dispatch(id: str, target: str = "manual") -> str:
    conn = _conn()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM todos WHERE id=?", (id,))
    row = cursor.fetchone()
    if not row:
        conn.close()
        return f"❌ 未找到任务 {id}"
        
    columns = [col[0] for col in cursor.description]
    t = dict(zip(columns, row))
    
    cursor.execute("UPDATE todos SET dispatch_last_run_at=?, updated_at=? WHERE id=?", (_now_iso(), _now_iso(), id))
    conn.commit()
    conn.close()
    
    if target == "manual":
        proj = t['project'] or "未知项目"
        prompt = f"""请在本地 IDE 执行以下任务：
项目: {proj}
任务标题: {t['title']}
任务ID: {t['id']}
背景详情: 
{t['description'] or '无'}
"""
        return f"✅ 手动派发成功。请将以下内容复制给本地 IDE：\n\n{prompt}"
    
    return f"❌ 暂不支持的 dispatch target: {target}"

def _todo_tick():
    now = _now_iso()
    conn = _conn()
    cursor = conn.cursor()
    
    # Bug 1 fix: use datetime() for robust comparison
    cursor.execute("""
        UPDATE todos SET status='pending', snoozed_until=NULL, updated_at=?
        WHERE status='snoozed' AND datetime(snoozed_until) <= datetime(?)
    """, (now, now))
    woken_count = cursor.rowcount
    
    # Bug 1 fix: use datetime()
    cursor.execute("""
        SELECT id, title, due_at, created_via FROM todos
        WHERE status IN ('pending','active')
          AND due_at IS NOT NULL
          AND notified_due_at IS NULL
          AND datetime(due_at) <= datetime(?, '+24 hours')
    """, (now,))
    due_soon = cursor.fetchall()
    
    for row in due_soon:
        tid = row[0]
        cursor.execute("UPDATE todos SET notified_due_at=?, updated_at=? WHERE id=?", (now, now, tid))
        print(f"[todo_tick] 提醒任务到期 {tid} {row[1]}") # Output to stdout for log tracing (Gap 1)
        
    if woken_count > 0:
        print(f"[todo_tick] 成功唤醒 {woken_count} 个任务") # Gap 1
        
    conn.commit()
    conn.close()
    
    if woken_count > 0 or due_soon:
        _render_markdown()

# Bug 5 fix: prevent duplicate job registration on module reload
_mgr = CronManager()
if not any(j.name == 'todo_tick' for j in _mgr.jobs.values()):
    _mgr.add_job('todo_tick', 'every_minute', _todo_tick)
